### PR TITLE
add support for deviantart source

### PR DESCRIPTION
**Pull request by ma3yta**
docs https://www.deviantart.com/developers/console/
example:
```bash
./styli.sh -g -l "deviantart" -s "car"
./styli.sh -g -l "deviantart" -s "tag:forestwoods"
./styli.sh -g -l "deviantart" -s "tag:wallpaper"
./styli.sh -g -a "sylviaritter"
./styli.sh -g --artist "wlop"
./styli.sh -g -l "deviantart"
```

### CODE REVIEW

**Review by thevinter — APPROVED** [review]
Thanks!

**Comment by ixzh** [comment]
hi I ran into this error: `curl: (3) URL using bad/illegal format or missing URL` when running the example commands...so it it working out of the box or do I need to configure something?

**Comment by ma3yta** [comment]
Hi @ixzh It works out of the box without any configuration. this is a warning (not an error), the wrong curl command was fixed in https://github.com/thevinter/styli.sh/pull/30. thanks for reporting.

**Comment by ixzh** [comment]
I run with -p option, and colors are updated... but the wallpaper doesn't change...

**Comment by thevinter** [comment]
Thanks!

**Pull request merged**
