### PR TITLE
Added directory switching so script can be launched from anywhere

### PR DESCRIPTION
**Pull request by jafonsoc**
Added `cd` to the script's directory so it can be run from anywhere and still read the `subreddits` file.

### CODE REVIEW

**Comment by duckunix** [comment]
I am not sure if this is the best way to go as I do not want the wallpaper image dropped in my bin dir, for example.  I am in the process of working on a patch to use the XDG standards.  I should have it later today (US) if my meetings stay low...

**Comment by thevinter** [comment]
As @duckunix stated I'm not sure saving the image in /bin is the best option. I'll wait for his proposal. In the meantime feel free to add the dir to the path as a temporary fix.

**Comment by jafonsoc** [comment]
That's a very good point. I guess I'll just add the path for now.

**Comment by duckunix** [comment]
I have added PR #6 with my approach.

Thanks.

**Comment by thevinter** [comment]
Closing since the changes have been submitted in #6

**Pull request closed without merging**
